---

name: 1.1.10
group: Corosync
labels: generic
description: |
  Test if corosync.conf files are identical across all nodes
remediation: |
  ## Abstract
  It is required that the corosync.conf files are identical across all nodes in the cluster.
  Usually, it is done automatically if you have configured csync2, but in case some manual intervention is made, it could cause cluster outages. 

  ## References
  - https://documentation.suse.com/sle-ha/15-SP3/html/SLE-HA-all/cha-ha-ycluster.html#sec-ha-installation-setup-csync2
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# check id. This value must not be changed over the life of this check
id: BA215C
